<a href="https://colab.research.google.com/github/mcrewcow/ChaginLab/blob/main/SkillboxMSEsubsgradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
a = np.array([2,5,0,6,8,10,6,7,5,7])
a
print(*a)

2 5 0 6 8 10 6 7 5 7


In [7]:
b = np.array([8,6,7,9,6,6,2,3,2,3])
c = 3 * a * 2 * b

In [8]:
print(*c)

96 180 0 324 288 360 72 126 60 126


In [9]:
a = np.array([9,6,7,7,0,1,6,8,1,2])
b = np.array([0,2,2,6,7,8,8,3,1,8])
c = 6 * a * 5 * b
print(*c)

0 360 420 1260 0 240 1440 720 30 480


In [10]:
a = np.array([2,5,0,6,8,10,6,7,5,7])
b = np.array([8,6,7,9,6,6,2,3,2,3])
print(*(a * b))

16 30 0 54 48 60 12 21 10 21


In [11]:
print(*(np.array([9,6,7,7,0,1,6,8,1,2]) * np.array([0,2,2,6,7,8,8,3,1,8])))

0 12 14 42 0 8 48 24 1 16


In [13]:
m1 = np.array([[2,1,7,4],[5,6,7,3],[9,8,2,12],[11,14,15,15]])
m1

array([[ 2,  1,  7,  4],
       [ 5,  6,  7,  3],
       [ 9,  8,  2, 12],
       [11, 14, 15, 15]])

In [16]:
print(*(m1.transpose()),sep = '\n')

[ 2  5  9 11]
[ 1  6  8 14]
[ 7  7  2 15]
[ 4  3 12 15]


In [17]:
m2 = np.array([[3,7,8,3,6],[2,5,9,4,13]])
print(*(m2.transpose()),sep = '\n')

[3 2]
[7 5]
[8 9]
[3 4]
[ 6 13]


In [20]:
from sympy import *
from sympy.plotting import plot
init_printing(use_unicode=False, wrap_line=False, no_global=True)
a1,a2 = symbols('a1,a2')
MSE = 1/4*((1*a1 + 2*a2 - 5)**2 + (5*a1 + 3*a2 - 6)**2 + (2*a1 + 4*a2 - 10)**2 + (3*a1 + 7*a2 - 8)**2)

In [21]:
MSE

In [45]:
MSE.subs({a1:0.395, a2:0.62})
MSEar = np.array([0.395,0.62])

In [31]:
msef2 = diff(MSE,a2)
msef2

In [32]:
msef1 = diff(MSE,a1)
msef1

In [33]:
msearr = np.array([msef1,msef2])

AttributeError: ignored

TypeError: ignored

In [41]:
msef1.subs({a1:0.395, a2:0.62})

In [42]:
msef2.subs({a1:0.395, a2:0.62})

In [44]:
MSEar2 = np.array([msef1.subs({a1:0.395, a2:0.62}),msef2.subs({a1:0.395, a2:0.62})])
MSEar2

array([-17.5375000000000, -28.7350000000000], dtype=object)

In [46]:
MSE2try = MSEar + 0.01 * (-MSEar2)
MSE2try

array([0.570375000000000, 0.907350000000000], dtype=object)

In [48]:
MSE.subs({a1: 0.57, a2: 0.91})

In [49]:
msef1.subs({a1: 0.57, a2: 0.91})

In [50]:
msef2.subs({a1: 0.57, a2: 0.91})

In [51]:
MSEar3 = np.array([msef1.subs({a1: 0.57, a2: 0.91}),msef2.subs({a1: 0.57, a2: 0.91})])

In [52]:
MSEar3

array([-7.45500000000000, -13.4000000000000], dtype=object)

In [56]:
MSE3try =  MSEar + 0.01 * (-MSEar2) + 0.01 * (-MSEar3)
MSE3try

array([0.644925000000000, 1.04135000000000], dtype=object)

In [57]:
MSE.subs({a1:0.645, a2:1.04})

In [58]:
MSEar4 = np.array([msef1.subs({a1: 0.645, a2: 1.041}),msef2.subs({a1: 0.645, a2: 1.041})])

In [59]:
MSEar4

array([-2.97950000000000, -6.56600000000000], dtype=object)

In [60]:
MSE4try =  MSEar + 0.01 * (-MSEar2) + 0.01 * (-MSEar3) + 0.01 * (-MSEar4)
MSE4try

array([0.674720000000000, 1.10701000000000], dtype=object)

In [61]:
MSE.subs({a1:0.674, a2:1.1})

In [62]:
MSEar5 = np.array([msef1.subs({a1: 0.674, a2: 1.1}),msef2.subs({a1: 0.674, a2: 1.1})])
MSEar5

array([-1.05700000000000, -3.59799999999999], dtype=object)

In [63]:
MSE5try =  MSEar + 0.01 * (-MSEar2) + 0.01 * (-MSEar3) + 0.01 * (-MSEar4) + 0.01 *(-MSEar5)
MSE5try

array([0.685290000000000, 1.14299000000000], dtype=object)

In [64]:
MSE.subs({a1:0.685,a2:1.142})

In [65]:
MSEar6 = np.array([msef1.subs({a1: 0.685, a2: 1.142}),msef2.subs({a1: 0.685, a2: 1.142})])
MSEar6

array([0.123500000000000, -1.70700000000000], dtype=object)

In [66]:
MSE6try =  MSEar + 0.01 * (-MSEar2) + 0.01 * (-MSEar3) + 0.01 * (-MSEar4) + 0.01 *(-MSEar5) + 0.01 * (-MSEar6)
MSE6try

array([0.684055000000000, 1.16006000000000], dtype=object)

In [67]:
MSE.subs({a1:0.684,a2:1.16})

In [68]:
MSEar7 = np.array([msef1.subs({a1: 0.684, a2: 1.16}),msef2.subs({a1: 0.684, a2: 1.16})])
MSEar7

array([0.518000000000001, -1.02800000000001], dtype=object)

In [69]:
MSE7try =  MSEar + 0.01 * (-MSEar2) + 0.01 * (-MSEar3) + 0.01 * (-MSEar4) + 0.01 *(-MSEar5) + 0.01 * (-MSEar6) + 0.01 * (-MSEar7)
MSE7try

array([0.678875000000000, 1.17034000000000], dtype=object)

In [70]:
MSE.subs({a1:0.678,a2:1.17})