<a href="https://colab.research.google.com/github/mcrewcow/ChaginLab/blob/main/skillbox10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
from sympy import *
import numpy

In [3]:
a1, a2 = symbols('a1,a2')

In [5]:
eq1 = -a1 + 7 * a2 + 34

In [6]:
eq2 = 8 * a1 + 8 * a2 + 48

In [7]:
nonlinsolve([eq1,eq2],[a1,a2])

FiniteSet((-1, -5))

In [9]:
eq3 = 4 * a1 + 7 * a2 + 4
eq4 = 3 * a1 - 4 * a2 + 3
nonlinsolve([eq3,eq4],[a1,a2])

FiniteSet((-1, 0))

In [11]:
eq5 = 8 * a1 - 4 * a2 - 64
eq6 = -3 * a1 + 3 * a2 + 21
nonlinsolve([eq5,eq6],[a1,a2])

FiniteSet((9, 2))

In [12]:
x1,x2,x3 = symbols('x1,x2,x3')
eqq1 = 5 * x1 + 7 * x2 - 5 * x3 + 47
eqq2 = -2 * x2 + 2 * x3 - 10
eqq3 = -4 * x1 - 8 * x2 -7 * x3 - 63
nonlinsolve([eqq1,eqq2,eqq3],[x1,x2,x3])

FiniteSet((-2, -6, -1))

In [13]:
x = Matrix([[-1,7],[8,8]])
x

Matrix([
[-1, 7],
[ 8, 8]])

In [14]:
mnozh = Matrix([-1,-5])
mnozh

Matrix([
[-1],
[-5]])

In [15]:
x * mnozh

Matrix([
[-34],
[-48]])

In [16]:
x4 = Matrix([[4,-7],[3,-4]])
mnozh1 = Matrix([-1,0])
x4 * mnozh1

Matrix([
[-4],
[-3]])

In [18]:
x5 = Matrix([[8,-4],[-3,3]])
mnozh2 = Matrix([9,2])
x5 * mnozh2

Matrix([
[ 64],
[-21]])

In [19]:
x6 = Matrix([[5,7,-5],[0,-2,2],[-4,-8,-7]])
mnozh3 = Matrix([-2,-6,-1])
x6 * mnozh3

Matrix([
[-47],
[ 10],
[ 63]])

In [20]:
x, y, z = symbols('x,y,z')
MSE = 1/6 * ((5 * x + 7 * y - 5 * z + 47) ** 2 + \
             (-2 * y + 2 * z - 10)**2 + \
             (-4 * x - 8 * y - 7 * z - 63)**2 + \
             (x + y + 2 * z + 1)**2 + \
             (2 * x - y + 2 * z + 4) ** 2 + \
             (4 * x + y + 4 * z + 2)**2)

In [21]:
MSE.subs({x:0,y:0,z:0})

1049.83333333333

In [22]:
MSEx = diff(MSE,x)
MSEx

20.6666666666667*x + 23.3333333333333*y + 8.33333333333333*z + 168.0

In [23]:
MSEy = diff(MSE,y)
MSEy

23.3333333333333*x + 40.0*y + 6.99999999999999*z + 284.0

In [24]:
MSEz = diff(MSE,z)
MSEz

8.33333333333333*x + 6.99999999999999*y + 34.0*z + 68.0

In [183]:
step = 0.01

In [184]:
point = next_point
point

array([-2.23017393855227, -5.78329893223984, 0.132468331754096],
      dtype=object)

In [185]:
grad = numpy.array([MSEx.subs({x:point[0],y:point[1],z:point[2]}),
                    MSEy.subs({x:point[0],y:point[1],z:point[2]}),
                    MSEz.subs({x:point[0],y:point[1],z:point[2]})])
grad

array([-11.9300003843923, 1.55792913313231, 13.4360479326915],
      dtype=object)

In [186]:
next_point = point - step * grad
next_point

array([-2.11087393470835, -5.79887822357116, -0.00189214757281966],
      dtype=object)

In [187]:
MSE.subs({x:next_point[0],y:next_point[1],z:next_point[2]})

52.5058598158850